### ISSUE TITLE
TW shows transport routes whilst using Move It mod

### ISSUE THREAD

**Issue by originalfoo** [earalov/Skylines-ToggleableWhiteness#3]
Original bug report at Move It mod: https://github.com/SamsamTS/CS-MoveIt/issues/11

When TW is enabled, it causes transport routes to be shown whenever the Move It mod is being used:

![region capture 13](https://user-images.githubusercontent.com/1386719/41098400-231bab50-6a53-11e8-8f32-8bbb3475add2.png)

Rail, air and sea routes are also shown.

While not generally a problem, it makes tweaking or detailing roads very cumbersome because the route lines obscure much of the road.

The only workaround I've found so far is to disable TW, but that involves save/load cycle which on my potato machine takes ~1 hour :/

**Comment by Videonauth** [comment]
Can confirm it, it is this mod interfering with move it mod.

**Comment by SamsamTS** [comment]
MoveItTool no longer inherits TransportTool which I believe was the source of the issue.

**Comment by Videonauth** [comment]
Yes it is working now as intended. Found the issue for the flashing in disaster screen too, it is if you place detectors outside the base 25 grid (81 tiles mod). Removing those outside and placing them inside the 25 grid the flashing stops. So i do not think that toggleable whiteness is the culprit here.

**Comment by originalfoo** [comment]
Confirmed fixed, closing issue.

@Videonauth I was having exact same issue with flashing disaster screen - thanks for the info!
